local GameLore = {
	Title = "Rooster Warrior",
	Sections = {
		{
			Id = "OpeningScene",
			Title = "Opening Scene",
			Body = table.concat({
				"You begin in a peaceful place called Suncrest Village, a small farming settlement surrounded by fields, forests, and old stone paths. Life there is simple. Farmers wake before sunrise, children run between the market stalls, and roosters crow from rooftops every morning.",
				"",
				"Most villagers believe the old stories are just legends.",
				"",
				"They speak of monsters called demons, dark creatures born from fear, anger, greed, and despair. According to the stories, these demons once nearly destroyed the world, and only a forgotten order of sacred warriors could stop them.",
				"",
				"That order was known as the Rooster Warriors.",
				"",
				"Now they are believed to be extinct.",
				"",
				"But something has changed.",
				"",
				"A strange black mist has begun appearing outside the village at night. Animals have gone missing. Crops rot overnight. People have started hearing screams from the woods. Shadows move where nothing should be alive.",
				"",
				"You are a young rooster from Suncrest Village. To everyone else, you are ordinary. Small. Unimportant.",
				"",
				"But on the day the village is attacked, everything changes.",
				"",
				"A minor demon emerges from the forest and attacks the farms. While the villagers panic, you fight back. Against all odds, you defeat the creature.",
				"",
				"After the battle, a wandering warrior named Master Kaien arrives. He studies you closely and notices an ancient mark hidden within your feathers - the symbol of a lost bloodline.",
				"",
				"He tells you the truth:",
				"",
				"You are not an ordinary rooster.",
				"",
				"You are descended from the ancient Rooster Warriors, legendary fighters chosen long ago to battle the darkness of the world.",
				"",
				"He warns you that this attack was only the beginning. Corruption is spreading across the land, and stronger demons are already awakening.",
				"",
				"If you stay in Suncrest Village, you will live and die as nothing.",
				"",
				"If you leave, you may become a warrior worthy of legend.",
				"",
				"That is where your journey begins.",
			}, "\n"),
		},
		{
			Id = "Chapter1",
			Title = "Chapter 1 - Suncrest Village",
			Body = table.concat({
				"This is the starting area of the game.",
				"",
				"Here the player learns the basics of movement, combat, quests, and enemies. The village feels safe at first, but demonic corruption is slowly taking hold.",
				"",
				"Main objectives:",
				"- Talk to villagers and learn about strange events",
				"- Defeat corrupted rats and wild beasts near the farms",
				"- Clear black mist from the wheat fields",
				"- Rescue villagers trapped near the forest edge",
				"- Enter the woods and defeat the first mini-boss, Mistfang Demon",
				"",
				"During these early quests, the player begins unlocking beginner combat abilities such as:",
				"- Peck Strike",
				"- Claw Combo",
				"- Dash Step",
				"- Battle Cry",
				"",
				"After defeating Mistfang Demon, Master Kaien appears and reveals the truth about the player's bloodline.",
				"",
				"He gives the player a mission:",
				"Travel beyond the village. Find the scattered remains of the Rooster Warriors. Discover why the demons are returning. Grow stronger before the darkness reaches every land.",
				"",
				"The player then leaves Suncrest Village through the eastern docks, beginning the first real adventure.",
			}, "\n"),
		},
	},
}

return GameLore
